### ISSUE TITLE
[feat]: Vanilla JS library

### ISSUE THREAD

**Issue by victoriusnet** [strapi/blocks-react-renderer#8]
### A clear and concise description of what the feature is

Hey!
It's good to have this lib, but why it's for React?
Since there is no docs available for Blocks how should we use it in other frameworks?

### Why should this feature be included?

Plain JS should be also supported

**Comment by remidej** [comment]
Hello, unfortunately we (the strapi team) decided to only maintain a React version of this library. It was a tough choice made because we have learnt that the cost of maintenance of these packages is high. We chose to do only 1 to show the community how it can be done, and React is the most popular option among Strapi users.

So we'll rely on the community to create other versions for different libraries. I invite you to post on the discord instead, as the issues here are only about the React version.
