### ISSUE TITLE
[feat]:  The blocks-react-renderer npm package is used to render the content configured in the Rich text (Blocks) rich text edit box. Only the content has no format.

### ISSUE THREAD

**Issue by happlybears-Leonard** [strapi/blocks-react-renderer#9]
### A clear and concise description of what the feature is

Hello, I am trying to use strapi to provide interface services to the front-end application in the content management backend.

The Rich text (Blocks) component of the strapi cms content management backend is configured with a rich text editing box. After editing the content in Rich text (Blocks), how can the front-end webpage obtain the data through the interface and restore it to a 1:1 ratio?

I used the blocks-react-renderer npm package, but only the content has no format. I hope that after writing the formatted content in Rich text (Blocks) in the strapi cms content management backend, the front-end interface requests the corresponding content and inserts it directly. , the displayed content and style can be consistent with those during editing, without the front-end website having to handle it by itself. This is too cumbersome and not open source enough.

### Why should this feature be included?

It is expected that after writing the formatted content in the rich text (Blocks) of the strapi cms content management backend, the front-end interface requests the corresponding content and inserts it directly. The displayed content and style can be consistent with those during editing, without the need for a front-end It would be too cumbersome for the website to handle it on its own and not open source enough.

**Comment by remidej** [comment]
Hello, thanks for filing this issue. I understand your point, but the current behavior is what we actually want, and we're not going to change it.

The goal of this renderer is to help developers with the logic to parse the Strapi Blocks format. We want the default experience to work, so that you can view your content, but we're not making any design decisions on purpose. Because:

- that would involve adding the design system as a dependency, most people won't need it, and it would increase the bundle size for everyone. It's also not made to be used outside of the Strapi admin, as it has dependencies on react router for example
- the vision for headless is to have the data completely separate from the rendering styles, and this package is consistent with it
- we want this package to be simple so that it can easily be forked into other languages
- it's quite hard to override pre-existing styles, we want to avoid that experience for users

Ideally we want users to define their own design by [providing their components](https://github.com/strapi/blocks-react-renderer#custom-components). If you don't want to do that, but also would like something a little prettier than raw HTML, I would recommend using Tailwind's [Typography package](https://tailwindcss.com/docs/typography-plugin), which basically makes raw HTML look good.
